export const ROUTES = {
  HOME: '/',
  COURSES: '/courses',
  COURSE_DETAIL: (slug: string) => `/courses/${slug}`,
  LESSON: (lessonId: string) => `/learn/${lessonId}`,
  PLAYGROUND: '/playground',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  VERIFY_EMAIL: '/verify-email',
  DASHBOARD: '/dashboard',
  PROFILE: '/profile',
  CERTIFICATE_VERIFY: (code: string) => `/verify-certificate/${code}`,
  BLOG: '/blog',
  BLOG_POST: (slug: string) => `/blog/${slug}`,
  PAYMENT_SUCCESS: '/payment/success',
  PAYMENT_CANCEL: '/payment/cancel',
  ADMIN: {
    ROOT: '/admin',
    OVERVIEW: '/admin',
    USERS: '/admin/users',
    COURSES: '/admin/courses',
    COURSE_EDITOR: (id: string) => `/admin/courses/${id}`,
    CATEGORIES: '/admin/categories',
    QUIZZES: '/admin/quizzes',
    COUPONS: '/admin/coupons',
    REPORTS: '/admin/reports',
    MODERATION: '/admin/moderation',
    BLOG: '/admin/blog',
  },
} as const;